### ISSUE TITLE
Wrong historical facts

### ISSUE THREAD

**Issue by nilsocket** [pim-book/programmers-introduction-to-mathematics#25]
I'm not a mathematician myself.

I have just skimmed through your book.
It seems you are trying a lot to say mathematics can exist without proof and can also be based on intuition. (Once again, I didn't read it completely).

Calculus as taught through out the academia, or discovered by newton is due to misunderstanding  of Indian calculus, says C.K.Raju.

I don't think you yourself know the real history, rather you were taught in such way. (Euro-Centrism).

Indian's have clear lineage(improvements done over period of time), for development of algebra, trigonometry, infinite series, calculus...

Out of nowhere Europeans have produced this work, as their own, without proper proofs and background.

I'm linking here one of the work by C.K.Raju here.
Which suggests calculus is stolen from India.
[Cultural Foundations Of Mathematics.pdf](https://github.com/pim-book/programmers-introduction-to-mathematics/files/4641558/Cultural.Foundations.Of.Mathematics.pdf)

Hoping, you will be as neutral as possible (If possible in your next-edition).

Thank you.

**Comment by j2kun** [comment]
Hi there,

Could you please refer to the specific passage in my book you think is factually incorrect? "Mathematics can exist without proof and can also be based on intuition" is not a claim I'm making, and is also not something that can be so trivially judged as true or false.

I'm not in a position to judge the matter of the origin of Calculus, though your linked book is not convincing. It apparently simply says, "How suspicious." As far as I understand, the Egyptians had algebra a few thousand years before Greeks did geometry, and the Persians developed trigonometry and algorithms. I have seen with my own eyes the original trigonometry books written by the Persians. So it is perfectly plausible to me that multiple cultures can develop mathematics independently. It happens even in modern history. To claim otherwise—and to suggest it must imply theft—is not in the spirit of mathematical community.

**Comment by nilsocket** [comment]
> To claim otherwise—and to suggest it must imply theft.

Nobody is claiming otherwise, he have given enough evidence, to suggest that, as people have stolen time-keeping from India (proof exist). Most of the initial published papers have no background
and are very cryptic to European civilization.

I doubt you have read the complete book within 20 minutes.

How valid is it to say somebody is wrong, without listening to other-side of the argument.

As I have said, I'm not a mathematician, I cannot point something wrong in your book.
I'm not saying some-thing is wrong in your book. I'm saying Historical facts are wrong.

This is the statement I keep hearing,
> So it is perfectly plausible to me that multiple cultures can develop mathematics independently.

And yet you include only Greek and Western as the only authoritative source which were developed properly and else as trash.

It is the powerful subjugating (i.e., through conquest or cultural domination) others and appropriating others work.
For ex: Their is no evidence Euclid existed, but it is very cleverly appropriated as Western.

There are many other appropriations, If one looks at the world history from ancient times. It's through subjugation of other civilization's other civilizations have risen (especially Western Civilization, we didn't go and colonize other civilizations in name teaching superior race or culture).

Having a historical background is also necessary.

> not in the spirit of mathematical community.

I don't think it is also the spirit of any morally correct mathematical community to disregard inventions of other countries and state it as independent re-discovery and keep including their invention despite enough evidence of work from other communities earlier.


You can find much more work done here:

> Mathematical Achievements of Pre-Modern Indian Mathematicians, Elsevier.

> Studies in Indian Mathematics and Astronomy: Selected Articles of Kripa Shankar Shukla, Springer.

I understand it is no way right to blame you, as you are taught such, and obviously it doesn't make any sense trying to convince you, as it is the mathematically society which should accept without prejudice.
Unfortunately it is biased.

Thank you.

**Comment by j2kun** [comment]
Locking this thread. Please find another outlet for this.
